version: '3'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "33060:3306"
    expose:
      - "33060"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    networks:
      - backend
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
  nest:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    networks:
      - backend
networks:
  backend:
    driver: "bridge"
