version: '3'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=12345
  nest:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
#    command:
#      - node ./dist/main.js
