version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
        environment:
          ENFILE: $ENFILE
      - image: mysql:5.7
        environment:
          MYSQL_USER: root
          MYSQL_DATABSE: sign
          MYSQL_ROOT_PASSWORD: $DB_PASSWORD
          MYSQL_PASSWORD: $DB_PASSWORD
    steps:
      - checkout
      - run: cat $DB_PASSWORD
      - run: npm install
      - run: echo -e $ENVFILE >> .env
      - run: node -v
      - run: cat .env
      - run: npm run lint
      - run: npm run test
